version: '3.8'
services:
  readme.user.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.user.mongo

    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.mongo.user:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.user.mongo:27017/

volumes:
  readme.mongo.user: