# Get comments by article Id

GET http://localhost:3000/api/comment/ab04593b-da99-4fe3-8b4b-e06d82e2efdd HTTP/1.1

###

# Create a new comment

POST http://localhost:3000/api/comment/create HTTP/1.1
Content-Type: application/json

{
  "articleId": "6d308040-96a2-4162-bea6-2338e9976540",
  "authorId": "665855e1d16d03e18a81b18f",
  "text": "Http created test comment"
}

###

# Delete a comment by comment id

DELETE http://localhost:3000/api/comment/delete/088aef23-daba-43fa-a16f-143902078bb6 HTTP/1.1

###