# Get comments by article Id

GET http://localhost:3000/api/comment/ab04593b-da99-4fe3-8b4b-e06d82e2efdd HTTP/1.1

###

# Create a new comment

POST http://localhost:3000/api/comment/create HTTP/1.1
Content-Type: application/json

{
  "articleId": "ab04593b-da99-4fe3-8b4b-e06d82e2efdd",
  "authorId": "random author id",
  "text": "Http created test comment"
}

###

# Delete a comment by comment id

DELETE http://localhost:3000/api/comment/delete/465db336-8e9f-4d36-8051-fb40501c542b HTTP/1.1

###